version: '3.8'
services:
  server:
    build:
      context: .
      target: server
    image: onlyoffice/trello-server:${PRODUCT_VERSION}

  client:
    build:
      context: .
      target: client
    image: onlyoffice/trello-client:${PRODUCT_VERSION}

  proxy:
    build:
      context: .
      target: proxy
    image: onlyoffice/trello-proxy:${PRODUCT_VERSION}
